module.exports = {
  BUCKET_ERROR: 'Este modelo no soporta imagen.',
  ERROR: 'Error',
  IMG_UPL_ERROR: 'Error al actualizar!',
  PASS_ERROR: 'Error con Contraseñas!',
  EMAIL_ERROR: 'Error con Email!',
  DUPLICATED_EMAIL: 'Email duplicado.',
  WRONG_CONFIRMATION_PASS: 'Las Contraseñas no coinciden.',
  WRONG_ID: 'Id Erróneo',
  WRONG_POST_ID: 'El id no corresponde a ningún post',
  WRONG_PERMISSIONS: 'Error de Permisos !',
  WRONG_USER_PASS: 'Usuario y Contraseña invalidos !',
  NO_EXISTS_USER_PASS: 'El Usuario o la Contraseña no existen.',
  NO_POST_ID: 'El id del post debe ser enviado',
  NO_COMMENT_ID: 'El id del comentario debe ser enviado',
  NO_DATA: 'Falta Data !',
  MIN_SEND_MSG: 'Mínimamente el mensaje tiene que ser modificado.',
  MIN_SEND_TIT_MSG: 'Mínimamente el titulo o mensaje tienen que ser modificados.',
  COMMENT_NOT_FROM_USER: 'El comentario no le pertenece al usuario.',
  POST_NOT_FROM_USER: 'El post no le pertenece al usuario.',
  NO_MESSAGE: 'El mensaje es requerido.',
  NO_FILE: 'El archivo es requerido.',
  NO_TYPE: 'El tipo de imagen a guardar es requerido.',
  NO_MESSAGE_TITLE: 'El mensaje y titulo son requeridos.',
  NO_USER_PASS: 'El usuario y la contraseña son requeridos.',
  NO_REGISTER_FIELDS: 'Usuario, contraseña, confirmacion contraseña y email son requeridos.',
  NO_AUTHORIZED: 'No autorizado !',
  INVALID_TOKEN: 'Token inválido.',
  INIT_SESSION: 'Por favor, inicie sesión.'
};
